-- This Query is what populates the materialized view that backs the map points for the asset map.

WITH CategoryTitles (id, title) AS (SELECT id, title
                                    FROM (VALUES ('non-profit', 'Non-profit'),
                                                 ('transportation', 'Transportation'),
                                                 ('business', 'Business'),
                                                 ('housing', 'Housing'),
                                                 ('health', 'Health'),
                                                 ('food', 'Food'),
                                                 ('education/youth', 'Education/Youth'),
                                                 ('community-center', 'Community Center'),
                                                 ('civic', 'Civic')) AS CategoryTitles (id, title)),
     AssetTypeTitle (id, title) AS (SELECT id, title
                                    FROM (VALUES ('bus_stops', 'Bus Stops'),
                                                 ('banks', 'Banks'),
                                                 ('polling_places', 'Polling Places'),
                                                 ('barbers', 'Barbers'),
                                                 ('libraries', 'Libraries'),
                                                 ('bike_share_stations', 'Bike Share Stations'),
                                                 ('dentists', 'Dentists'),
                                                 ('museums', 'Museums'),
                                                 ('nail_salons', 'Nail Salons'),
                                                 ('health_centers', 'Health Centers'),
                                                 ('gas_stations', 'Gas Stations'),
                                                 ('achd_clinics', 'ACHD Clinics'),
                                                 ('farmers_markets', 'Farmers Markets'),
                                                 ('apartment_buildings', 'Apartment Buildings'),
                                                 ('veterans_social_orgs', 'Veterans Social Orgs'),
                                                 ('park_and_rides', 'Park and Rides'),
                                                 ('universities', 'Universities'),
                                                 ('coffee_shops', 'Coffee Shops'),
                                                 ('homeless_shelters', 'Homeless Shelters'),
                                                 ('public_buildings', 'Public Buildings'),
                                                 ('restaurants', 'Restaurants'),
                                                 ('wic_vendors', 'Wic Vendors'),
                                                 ('faith', 'Faith'),
                                                 ('senior_centers', 'Senior Centers'),
                                                 ('child_care_centers', 'Child Care Centers'),
                                                 ('community_nonprofit_orgs', 'Community Nonprofit Orgs'),
                                                 ('nursing_homes', 'Nursing Homes'),
                                                 ('post_offices', 'Post Offices'),
                                                 ('doctors_offices', 'Doctors Offices'),
                                                 ('laundromats', 'Laundromats'),
                                                 ('supermarkets', 'Supermarkets'),
                                                 ('schools', 'Schools'),
                                                 ('bars', 'Bars'),
                                                 ('hotels', 'Hotels'),
                                                 ('va_facilities', 'VA Facilities'),
                                                 ('affordable_housing', 'Affordable Housing'),
                                                 ('family_support_centers', 'Family Support Centers'),
                                                 ('pharmacies', 'Pharmacies'),
                                                 ('parks_and_facilities', 'Parks And Facilities'),
                                                 ('food_banks', 'Food Banks'),
                                                 ('hair_salons', 'Hair Salons'),
                                                 ('acha_community_sites', 'ACHA Community Sites'),
                                                 ('rec_centers', 'Rec Centers'),
                                                 ('wic_offices', 'WIC Offices')) AS AssetTypeTitle (id, title)),
     Categories (a_type, category) AS (SELECT a_type, category
                                       FROM (VALUES ('bus_stops', 'transportation'),
                                                    ('banks', 'business'),
                                                    ('polling_places', 'civic'),
                                                    ('barbers', 'business'),
                                                    ('libraries', 'civic'),
                                                    ('bike_share_stations', 'transportation'),
                                                    ('dentists', 'health'),
                                                    ('museums', 'education/youth'),
                                                    ('nail_salons', 'business'),
                                                    ('health_centers', 'health'),
                                                    ('gas_stations', 'business'),
                                                    ('achd_clinics', 'health'),
                                                    ('farmers_markets', 'food'),
                                                    ('apartment_buildings', 'housing'),
                                                    ('veterans_social_orgs', 'non-profit'),
                                                    ('park_and_rides', 'transportation'),
                                                    ('universities', 'education/youth'),
                                                    ('coffee_shops', 'business'),
                                                    ('homeless_shelters', 'housing'),
                                                    ('public_buildings', 'civic'),
                                                    ('restaurants', 'food'),
                                                    ('wic_vendors', 'food'),
                                                    ('faith-based_facilities', 'non-profit'),
                                                    ('senior_centers', 'community-center'),
                                                    ('child_care_centers', 'education/youth'),
                                                    ('community_nonprofit_orgs', 'non-profit'),
                                                    ('nursing_homes', 'health'),
                                                    ('post_offices', 'civic'),
                                                    ('doctors_offices', 'health'),
                                                    ('laundromats', 'business'),
                                                    ('supermarkets', 'food'),
                                                    ('schools', 'education/youth'),
                                                    ('bars', 'business'),
                                                    ('hotels', 'business'),
                                                    ('va_facilities', 'community-center'),
                                                    ('affordable_housing', 'housing'),
                                                    ('family_support_centers', 'community-center'),
                                                    ('pharmacies', 'health'),
                                                    ('parks_and_facilities', 'civic'),
                                                    ('food_banks', 'food'),
                                                    ('hair_salons', 'business'),
                                                    ('acha_community_sites', 'community-center'),
                                                    ('rec_centers', 'community-center'),
                                                    ('wic_offices', 'civic')) AS Categories (a_type, category))
SELECT *,
       (SELECT title
        FROM CategoryTitles
        WHERE id = category) AS category_title,
    (SELECT title
        FROM AssetTypeTitle
        WHERE id = asset_type) AS asset_type_title
FROM (SELECT asset_id                                                         as id,
             name,
             asset_type,
             (SELECT category FROM Categories WHERE a_type = asset_type) AS category,
             street_address,
             city,
             state,
             zip_code,
             _geom
      FROM "5c7825d2-6814-40c7-aefe-3d0f3d6f22e7") as raw;
